[bot]
# стейт False / True выключен включен бот
state = False

# токен бота из @botfather
token = HERE_TOKEN

# айди админов, они могут юзать тг бота. если их много - через запятую 123,123,123
admins = 123

[proxy]
# если нужны прокси то вводи сюда. протокол хттп
# если не нужны оставь поля пустыми
host =
port =
user =
pass =

[notifications]
info = true
warning = true
error = true
trash = false
photo = true