NEED_SHOP_AFTER_RIP = True # бакалейщик после смерти
NEED_SHOP_AFTER_PVP_EVADE = True # бакалейщик после пвп доджа
NEED_CLAIM_DAILY = True # при сборе наград нужны ли дейлики?
NEED_CLAIM_MAIL = True # при сборе наград нужна ли почта?
NEED_CLAIM_ACHIV = True # при сборе наград нужны ли ачивки?
NEED_CLAIM_CLAN = True # при сборе наград нужен ли клан?
NEED_CLAIM_ALI = True # при сборе наград нужен ли альянс?
NEED_CLAIM_BATTLE_PASS = True # при сборе наград нужен ли батл пасс?
NEED_CLAIM_DONATE_SHOP = True # при сборе наград нужен ли донат шоп?